language: rust
cache: cargo
virt: lxd

before_install:
  - rustup component add rustfmt clippy

script:
  - cargo build --benches --verbose
  - cargo test --verbose
  - cargo fmt --all -- --check
  - cargo clippy -- -D clippy::all

deploy:
  provider: cargo
  token:
    secure: "QChykAD/vntzVNHePGuCHRNyLJwiqRAqIYw1uCqWVaca5IYMuItv2Qs6hShWt8AVQ631ZC5O5mnYTsPyxO3ZLZAPM/UEtmJiR9zf7v9DJyPPyyaT9kw+YrELVwit/xab2uJzJIZ1mBHSx0An/67gfdTITLjQmW2UVPhu3pdUz3rSrYBxp2quD7OgMfHeXXP8yk2xtZIXQ2mcNuNPnEkCk/siGTyS1Py/cpEFBsGfHSMPLyZq9Mn/PFPttPtebZiWUPvfDHFqbTd73SB2DmJrrdJ/rpeiHKNuPJUbc8qA1yDQjLATUNmDXjg+q8gcPIraj+zifeR6M+TIG0tLPU1NKVI1Oxta1CUurV+m5qY9YmFxtNyTNquOI4ehbckXADgZhIOLDD9/rfYETXdkxXwYh0WozNOp+yqZj+wGqFfxB3+DfMRKk/ooYQqCYJ2Pun+SzTSnv2REa0Sa70a67hADMV6h6qfumEq3XxgKouNHd3gg+b1urB6JKfL8RI9SrOwKgkU/mBl+qCzP+UwAUPqnzp/r9GONm86gsUZXuhwDJmru30B9YLOrzwnKdGjZEBWDV6OuT5p9e1R+rot069qeTqMOiu8ZAAulttBAEpFoG99vTW1elE3aSBasVa9/YS0M1kY4n4Yz8GTP8w8p9WXM6hX6MU8iR//hPsNHQiNwJws="
  on:
    tags: true
    condition: '"$TRAVIS_TAG" =~ ^v[0-9].+$'
